application: mehtatoourmadness-1199
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /images
  static_dir: static/images
  mime_type: image/jpg

- url: .*
  script: wedding.app

libraries:
- name: webapp2
  version: "2.5.1"